### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Saniya-Korti**
This project is a Blog API that allows users to create, read, update, and delete blog posts. It is designed to handle CRUD operations with a focus on performance and simplicity.Built using Spring Boot and integrated with MySQL for data storage, ensuring efficient management of blog data.The API includes user authentication and authorization features for secure access to blog content.

### CODE REVIEW

**Review by Saniya-Korti — COMMENTED** [review]
This project is a Blog API that allows users to create, read, update, and delete blog posts. It is designed to handle CRUD operations with a focus on performance and simplicity.Built using Spring Boot and integrated with MySQL for data storage, ensuring efficient management of blog data.The API includes user authentication and authorization features for secure access to blog content.

**Comment by Saniya-Korti** [comment]
/

**Review by Saniya-Korti — COMMENTED** [review]
// This project is a Blog API that allows users to create, read, update, and delete blog posts.
// It is designed to handle CRUD operations with a focus on performance and simplicity.
// Built using Spring Boot and integrated with MySQL for data storage, ensuring efficient management of blog data.
// The API includes user authentication and authorization features for secure access to blog content.

**Comment by gautamprajapat** [comment]
thanks

**Pull request merged**
